import "./styles.css";
import {register,login,logout,api} from "./api.js";
import {state,refresh} from "./state.js";
import {games,startGame,init3D} from "./games.js";

const app=document.querySelector("#app");
let view="home";
function shell(){app.innerHTML=`<div id="bg3d"></div><header class="top glass"><button class="brand" data-nav="home">✦ ARCADE<span>VERSE</span></button><nav><button data-nav="home">Home</button><button data-nav="games">Games</button><button data-nav="pass">Battle Pass</button><button data-nav="shop">Shop</button><button data-nav="profile">Profile</button></nav><div class="wallet">🪙 <b id="coins">0</b> · <b id="level">Lv.1</b><button id="authBtn" class="mini">Login</button></div></header><main id="main"></main><div id="toast"></div><footer>ARCADEVERSE V2 · Full Stack</footer>`;init3D()}
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
function nav(v){view=v;render()}
function header(){document.querySelector("#coins").textContent=state.user?.coins?.toLocaleString("de-DE")||0;document.querySelector("#level").textContent=`Lv.${state.user?.level||1}`;document.querySelector("#authBtn").textContent=state.user?"Logout":"Login"}
function render(){header();const m=document.querySelector("#main");if(view==="home")home(m);if(view==="games")gamesView(m);if(view==="play")playView(m);if(view==="shop")shopView(m);if(view==="pass")passView(m);if(view==="profile")profileView(m)}
function cards(){return games.map(g=>`<article class="card glass" data-game="${g.id}"><span class="tag">${g.tag}</span><div class="big">${g.icon}</div><h3>${g.name}</h3><p>${g.desc}</p><button class="primary">PLAY →</button></article>`).join("")}
function home(m){m.innerHTML=`<section class="hero"><div><small>SEASON 01 · NEON HORIZON</small><h1>PLAY.<br><em>COLLECT.</em><br>UNLOCK.</h1><p>Die vollständige Arcade-Plattform: Minispiele, globale Highscores, Cloud-Saves, Daily Challenges, Battle Pass und Cosmetics.</p><button class="primary" data-nav="games">JETZT SPIELEN →</button></div><div class="avatar glass"><div class="bot">🤖</div><span>ONLINE ARCADE</span><b>${state.user?`Willkommen, ${state.user.displayName}`:"Spiele ohne Login oder erstelle einen Account"}</b></div></section><div class="head"><h2>Minispiele</h2></div><div class="grid">${cards()}</div>`}
function gamesView(m){m.innerHTML=`<div class="title"><small>ARCADE</small><h1>Wähle dein Spiel</h1><p>Jede Runde kann Coins, XP und einen neuen Highscore bringen.</p></div><div class="grid">${cards()}</div>`}
function playView(m){m.innerHTML=`<div class="playtop"><button class="secondary" data-nav="games">← Games</button><div><small>ARCADE RUN</small><h2 id="playName">Game</h2></div><strong id="score">0</strong></div><div id="stage" class="stage glass"></div><div class="hint" id="hint">Bereit?</div>`;const id=window.currentGame;document.querySelector("#playName").textContent=games.find(g=>g.id===id).name;startGame(id,document.querySelector("#stage"),r=>{state.user=r.user;header();toast(`+${r.coinsAwarded} Coins · +${r.xpAwarded} XP`);});}
function shopView(m){m.innerHTML=`<div class="title"><small>COSMETICS</small><h1>Item Shop</h1><p>Dein Inventar wird serverseitig gespeichert.</p></div><div id="shop" class="shop"></div>`;api("/shop").then(items=>{m.querySelector("#shop").innerHTML=items.map(i=>{const own=state.inventory.some(x=>x.id===i.id);return `<article class="item glass"><div>${i.icon}</div><small>${i.rarity}</small><h3>${i.name}</h3><p>${i.type}</p><button class="secondary buy" data-id="${i.id}">${own?"✓ Im Inventar":"🪙 "+i.price}</button></article>`}).join("");m.querySelectorAll(".buy").forEach(b=>b.onclick=async()=>{try{const r=await api("/shop/buy/"+b.dataset.id,{method:"POST"});state.user=r.user;await refresh();render();toast("Cosmetic freigeschaltet!")}catch(e){toast(e.message)}})});}
function passView(m){m.innerHTML=`<div class="title"><small>SEASON 01</small><h1>Battle Pass</h1><p>Level dich hoch und beanspruche deine Rewards.</p></div><div class="pass glass" id="pass"></div>`;api("/pass").then(p=>{const xp=state.user?.xp||0,lv=state.user?.level||1;m.querySelector("#pass").innerHTML=`<h2>${p.name}</h2><p>Level ${lv} · ${xp} XP</p><div class="passgrid">${p.rewards.map(r=>`<div class="passitem"><small>TIER ${r.tier}</small><div>${r.cosmetic?.icon||"🪙"}</div><b>${r.cosmetic?.name||r.coins+" Coins"}</b><button class="claim" data-id="${r.id}" ${lv<r.tier?"disabled":""}>${lv>=r.tier?"CLAIM":"🔒"}</button></div>`).join("")}</div>`;m.querySelectorAll(".claim").forEach(b=>b.onclick=async()=>{try{const r=await api("/pass/claim/"+b.dataset.id,{method:"POST"});state.user=r.user;await refresh();render();toast("Reward beansprucht!")}catch(e){toast(e.message)}})})}
async function profileView(m){if(!state.user){authModal();return}const scores=await Promise.all(games.map(async g=>({g,rows:await api("/leaderboard/"+g.id)})));m.innerHTML=`<div class="title"><small>PROFILE</small><h1>${state.user.displayName}</h1><p>Level ${state.user.level} · ${state.user.xp} XP · 🪙 ${state.user.coins}</p></div><div class="stats"><div class="glass">🪙<b>${state.user.coins}</b></div><div class="glass">⭐<b>Level ${state.user.level}</b></div><div class="glass">🎨<b>${state.inventory.length} Items</b></div></div><h2>Global Leaderboards</h2><div class="leader">${scores.map(x=>`<section class="glass"><h3>${x.g.icon} ${x.g.name}</h3>${x.rows.slice(0,5).map(r=>`<div><span>#${r.rank} ${r.displayName}</span><b>${r.score}</b></div>`).join("")}</section>`).join("")}</div>`}
function authModal(){document.querySelector("#toast").textContent="Bitte einloggen oder registrieren.";document.querySelector("#toast").classList.add("show");setTimeout(()=>document.querySelector("#toast").classList.remove("show"),2500);const email=prompt("E-Mail");if(!email)return;const password=prompt("Passwort (mind. 8 Zeichen)");if(!password)return;login({email,password}).then(async r=>{state.user=r.user;await refresh();render()}).catch(()=>register({email,password,displayName:prompt("Anzeigename")||"Player"}).then(async r=>{state.user=r.user;await refresh();render()}).catch(e=>toast(e.message)))}
document.addEventListener("click",e=>{const n=e.target.closest("[data-nav]");if(n)nav(n.dataset.nav);const g=e.target.closest("[data-game]");if(g){if(!state.user){authModal();return}window.currentGame=g.dataset.game;nav("play")}if(e.target.id==="authBtn"){if(state.user){logout();state.user=null;toast("Ausgeloggt.");render()}else authModal()}})
shell();refresh().then(ok=>{if(ok)render();else render()});
